qip-0005: cross shard transactions
quai-network/qips pull request #16
Opened 2023-12-01 18:29 UTC by wizeguyy

2023-12-05 15:34 UTC, alanorwick approved these changes

2023-12-05 17:47 UTC, gameofpointers requested changes
We should add the Pending Etx rollup specification as its part of the header and is consensus breaking

2023-12-05 22:28 UTC, kiltsonfire requested changes
We need to add a couple of items.  Specifically, we need to have dequeing on the dom blocks per our discussion.  This would mean we order the transactions by block, compute a constant rate based on expectation of the next dom block and process transactions so that each block has a consistent number of incoming ETXs for the Quai ledger.  For the QU ledger, I do not think there is a need to dequeue, but rather just add all UTXOs to the set at the destination all at once because it is a relatively lightweight computation.  We may want to consider also "aging" in the UTXO set to make the likelihood of re computation if a dom block is orphaned less impactful on the re computation of the set.

2023-12-07 18:28 UTC, wizeguyy commented
> We should add the Pending Etx rollup specification as its part of the header and is consensus breaking

I've updated the spec to handle far-coordinate referencing (aka rollups). See the "Far-Coordinate ETX Referencing" section.

2023-12-11 16:34 UTC, merged